//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Similitud.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class segmentos
    {
        public int id_segment { get; set; }
        public string track_id { get; set; }
        public double start { get; set; }
        public double duration { get; set; }
        public double confidence { get; set; }
        public double loudness_start { get; set; }
        public double loudness_max_time { get; set; }
        public double loudness_max { get; set; }
        public Nullable<double> pitch1 { get; set; }
        public Nullable<double> pitch2 { get; set; }
        public Nullable<double> pitch3 { get; set; }
        public Nullable<double> pitch4 { get; set; }
        public Nullable<double> pitch5 { get; set; }
        public Nullable<double> pitch6 { get; set; }
        public Nullable<double> pitch7 { get; set; }
        public Nullable<double> pitch8 { get; set; }
        public Nullable<double> pitch9 { get; set; }
        public Nullable<double> pitch10 { get; set; }
        public Nullable<double> pitch11 { get; set; }
        public Nullable<double> pitch12 { get; set; }
        public Nullable<double> timbre1 { get; set; }
        public Nullable<double> timbre2 { get; set; }
        public Nullable<double> timbre3 { get; set; }
        public Nullable<double> timbre4 { get; set; }
        public Nullable<double> timbre5 { get; set; }
        public Nullable<double> timbre6 { get; set; }
        public Nullable<double> timbre7 { get; set; }
        public Nullable<double> timbre8 { get; set; }
        public Nullable<double> timbre9 { get; set; }
        public Nullable<double> timbre10 { get; set; }
        public Nullable<double> timbre11 { get; set; }
        public Nullable<double> timbre12 { get; set; }
        public Nullable<int> fingerprint_code { get; set; }
    }
}
