//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Similitud.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class similares
    {
        public int similarity_id { get; set; }
        public string track_id { get; set; }
        public string track_id_similar1 { get; set; }
        public string track_id_similar2 { get; set; }
        public string track_id_similar3 { get; set; }
        public string track_id_similar4 { get; set; }
        public string track_id_similar5 { get; set; }
    }
}
