//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Similitud.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class similarity
    {
        public string target { get; set; }
        public string similar { get; set; }
        public long ID { get; set; }
    
        public virtual artists artists { get; set; }
        public virtual artists artists1 { get; set; }
    }
}
